services:
  - type: web
    name: lifelink-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

